### ISSUE TITLE
crd example build tasks fails

### ISSUE THREAD

**Issue by nagkumar** [cdk8s-team/cdk8s#1040]
```
iac\cdk8s\java\crd>npm run build

> crd-java@0.0.0 build
> cdk8s import --language java

Importing k8s v1.25.0...
Importing resources, this may take a few moments...
k8s
Importing resources, this may take a few moments...
jenkins.io
  jenkins.io/jenkins
Importing resources, this may take a few moments...
mattermost.com
  mattermost.com/clusterinstallation
Importing resources, this may take a few moments...
sample-controller.k8s.io
  sample-controller.k8s.io/foo
Error: Key '<<' contains non standard characters (Must match regex '/^(\w|\.|\/|-|#|,)*$/')
    at SafeReviver._sanitizeObj (d:\Apps\Dev\langs\scripting\js\Node\16.x\16.17.1\node_modules\cdk8s-cli\lib\reviver.js:40:23)
    at SafeReviver._sanitizeObj (d:\Apps\Dev\langs\scripting\js\Node\16.x\16.17.1\node_modules\cdk8s-cli\lib\reviver.js:47:22)
    at SafeReviver._sanitizeObj (d:\Apps\Dev\langs\scripting\js\Node\16.x\16.17.1\node_modules\cdk8s-cli\lib\reviver.js:47:22)
    at SafeReviver._sanitizeObj (d:\Apps\Dev\langs\scripting\js\Node\16.x\16.17.1\node_modules\cdk8s-cli\lib\reviver.js:47:22)
    at SafeReviver.sanitize (d:\Apps\Dev\langs\scripting\js\Node\16.x\16.17.1\node_modules\cdk8s-cli\lib\reviver.js:31:14)
    at safeParseYaml (d:\Apps\Dev\langs\scripting\js\Node\16.x\16.17.1\node_modules\cdk8s-cli\lib\util.js:155:17)
    at safeParseCrds (d:\Apps\Dev\langs\scripting\js\Node\16.x\16.17.1\node_modules\cdk8s-cli\lib\import\crd.js:147:46)
    at Function.fromSpec (d:\Apps\Dev\langs\scripting\js\Node\16.x\16.17.1\node_modules\cdk8s-cli\lib\import\crd.js:120:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

when  serving version is upgraded to v0.16.0 to v0.18.0 (which is the latest)

![image](https://user-images.githubusercontent.com/332234/197697722-de98b3b6-b0eb-4360-9b4b-1199cee50d54.png)

**Comment by sumupitchayan** [comment]
This error message is due to the fact that the yaml CRD file uses the `<<` characters, which cdk8s filters for when importing CRD's. There is no way around this error other than for the yaml manifest to change, since cdk8s uses that as its source of truth.

However, in this [CRD's latest version](https://github.com/knative/serving/releases/) (v1.9.2 as of the time of writing) the invalid `<<` characters are dropped and I was able to successfully import this CRD in a cdk8s java project. You add this link to your cdk8s.yaml file: [https://github.com/knative/serving/releases/download/knative-v1.9.2/serving-crds.yaml](https://github.com/knative/serving/releases/download/knative-v1.9.2/serving-crds.yaml)

**Comment by iliapolo** [comment]
Yeah the `<<` characters came from a `merge` directive, which YAML technically supports but its very uncommon to exist in k8s manifests, so its ok for cdk8s to fail on it. 

@sumupitchayan Can you update the CRD version we use though to the latest and correct one?
