### ISSUE TITLE
Error: http error: getaddrinfo ENOTFOUND registry.npmjs.org

### ISSUE THREAD

**Issue by OperationalFallacy** [cdk8s-team/cdk8s#1042]
### Description of the bug:

The cli is trying to call registry.npmjs.org on every run, and assumes the network is on, DNS resolves, and the site is accessible. 

It is a problem because of delays in synth, dev experience suffers.

And it is problematic to use in corp environments.

### Reproduction Steps:

Set up the vanilla typescript app, and run the synth while the network connection is off.

### Error Log:

```
➜  app git ✗ time (npm run compile && yarn cdk8s synth)

> app@1.0.0 compile
> tsc --build

yarn run v1.22.17
warning ../package.json: No license field
$ /path/cdk8s/app/node_modules/.bin/cdk8s synth
/path/cdk8s/app/node_modules/cdk8s/lib/_loadurl.js:39
    throw new Error(`http error: ${err.message}`);
    ^

Error: http error: getaddrinfo ENOTFOUND registry.npmjs.org
    at RedirectableRequest.<anonymous> (/path/cdk8s/app/node_modules/cdk8s/lib/_loadurl.js:39:11)
    at Object.onceWrapper (node:events:510:26)
    at RedirectableRequest.emit (node:events:390:28)
    at ClientRequest.eventHandlers.<computed> (/path/cdk8s/app/node_modules/cdk8s/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
------------------------------------------------------------------------------------------------
A new version undefined of cdk8s-cli is available (current 2.1.26).
Run "npm install -g cdk8s-cli" to install the latest version on your system.
For additional installation methods, see https://cdk8s.io/docs/latest/getting-started
------------------------------------------------------------------------------------------------
Synthesizing application
  - dist/app.k8s.yaml
 ``` 

### Environment:

Any

---

This is :bug: Bug Report

**Comment by iliapolo** [comment]
Thanks for reporting. I think there are two issues here:

1. The CLI shouldn't print the upgrade message if it failed to fetch it.
2. We can provide a configuration file setting that disables this check.

In the meantime, you can pass `--no-check-upgrade` on any cdk8s command to disable this check.
