### ISSUE TITLE
Fix for Python webservice.py code

### ISSUE THREAD

**Issue by tucktuck9** [cdk8s-team/cdk8s#1123]
### Description of the bug:
Running the Python `webservice.py` in the [Getting started](https://cdk8s.io/docs/latest/getting-started/) guide with `cdk8s synth` results in the following error: `AttributeError: 'Node' object has no attribute 'unique_id'`. The issue is with this line of code in **webservice.py**: `label = {'app': Node.of(self).unique_id}`. When I updated the code to `label = {'app': Node.of(self).id}` and ran `cdk8s synth` again, it worked.

### Reproduction Steps:
1. Copy/run [main.py](https://cdk8s.io/docs/latest/getting-started/#importing-constructs-for-the-kubernetes-api) with `cdk8s synth`, then apply the generated manifest with `kubectl apply -f dist/hello.k8s.yaml`.
2. Copy/run [webservice.py](https://cdk8s.io/docs/latest/getting-started/#abstraction-through-constructs) with `cdk8s synth` results in the error shown in error log.

### Error Log:
**webservice.py**
```
Synthesizing application
Traceback (most recent call last):
File "/Users/myuname/playground/cdk8s-getting-started/main.py", line 16, in <module>
MyChart(app, "hello")
File "/Users/myuname/.local/share/virtualenvs/cdk8s-getting-started-z00gfbuA/lib/python3.11/site-packages/jsii/_runtime.py", line 111, in __call__
inst = super().__call__(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/myuname/playground/cdk8s-getting-started/main.py", line 11, in __init__
WebService(self, 'hello', image='paulbouwer/hello-kubernetes:1.7', replicas=2)
File "/Users/myuname/.local/share/virtualenvs/cdk8s-getting-started-z00gfbuA/lib/python3.11/site-packages/jsii/_runtime.py", line 111, in __call__
inst = super().__call__(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/myuname/playground/cdk8s-getting-started/webservice.py", line 14, in __init__
label = {'app': Node.of(self).unique_id}
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Node' object has no attribute 'unique_id'
Error: command "pipenv run python main.py " at /Users/myuname/playground/cdk8s-getting-started returned a non-zero exit code 1
at ChildProcess.<anonymous> (/opt/homebrew/Cellar/cdk8s/2.1.83/libexec/lib/node_modules/cdk8s-cli/lib/util.js:51:27)
at Object.onceWrapper (node:events:628:26)
at ChildProcess.emit (node:events:513:28)
at ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

### Environment:
  - **Framework Version**: Latest
  - **OS**: macOS

### Other:
The issue is with this line of code in **webservice.py**: `label = {'app': Node.of(self).unique_id}`. When I updated the code to `label = {'app': Node.of(self).id}` and ran `cdk8s synth` again, it worked.

---

This is :bug: Bug Report

**Comment by alexcogojocaru** [comment]
Same problem here, from the [constructs repository](https://github.com/aws/constructs) it seems that the field's name is [id](https://github.com/aws/constructs/blob/10.x/src/construct.ts#L49).

**Comment by sumupitchayan** [comment]
Looks like this has already been [fixed](https://github.com/cdk8s-team/cdk8s/pull/1191/files)!
