### ISSUE TITLE
error during ckd8s init run 

### ISSUE THREAD

**Issue by bparinas** [cdk8s-team/cdk8s#1387]
### Description of the bug:

i tried to follow the python setup howto but during initialization i'm getting this error below. any advise?

[hello]$ cdk8s init pythonapp
/usr/local/lib/node_modules/cdk8s-cli/node_modules/cdk8s/lib/api-object.js:66
        this.name = props.metadata?.name ?? this.chart.generateObjectName(this);
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cdk8s-cli/node_modules/cdk8s/lib/index.js:17:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

### Environment:

  - **Framework Version**:
  - **OS**:

### Other:

---

This is :bug: Bug Report

**Comment by vinayak-kukreja** [comment]
Hey @bparinas , thank you for reporting this. 

Could you tell me what `cdk8s`, `pipenv` and `python` version were you using?
