### ISSUE TITLE
cdk8s import github:grafana/agent@v0.35.4  results in unsupported protocol github

### ISSUE THREAD

**Issue by Vad1mo** [cdk8s-team/cdk8s#1444]
I am trying to import a CRD that is listed on https://doc.crds.dev/github.com/grafana/agent@v0.35.4 into cdk8s.

From the `cdk8s import --help` I got the description that `cdk8s import github:crossplane/crossplane@0.14.0  Imports constructs for a GitHub repo using doc.crds.dev` should work.

I tried `cdk8s import github:crossplane/crossplane@0.14.0`and the result was successful

```
❯ cdk8s import github:crossplane/crossplane@0.14.0
Importing resources, this may take a few moments...
apiextensions.crossplane.io
  apiextensions.crossplane.io/compositeresourcedefinition
  apiextensions.crossplane.io/composition
pkg.crossplane.io
  pkg.crossplane.io/configuration
  pkg.crossplane.io/configurationrevision
  pkg.crossplane.io/controllerconfig
  pkg.crossplane.io/provider
  pkg.crossplane.io/providerrevision
meta.pkg.crossplane.io
  meta.pkg.crossplane.io/configuration
  meta.pkg.crossplane.io/provider
```

### Description of the bug:

When I however try to import `github:grafana/agent@v0.35.4` I see this error:
```
❯ cdk8s import github:grafana/agent@v0.35.4
Error: unsupported protocol github:
    at download (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/util.js:177:19)
    at ImportCustomResourceDefinition.fromSpec (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/crd.js:108:52)
    at matchImporter (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:35:49)
    at async importDispatch (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:10:26)
    at async Object.handler (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/cli/cmds/import.js:31:9)

```

### Reproduction Steps:

```
cdk8s import github:grafana/agent@v0.35.4
```

### Error Log:

```
Error: unsupported protocol github:
    at download (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/util.js:177:19)
    at ImportCustomResourceDefinition.fromSpec (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/crd.js:108:52)
    at matchImporter (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:35:49)
    at async importDispatch (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:10:26)
    at async Object.handler (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/cli/cmds/import.js:31:9)

```

### Environment:

  - **Framework Version**: cdk8s 2.5.0, as well as older versions 
  - **OS**: MacOS

### Other:

---

This is :bug: Bug Report

**Comment by pbar1** [comment]
Hey - I was also running into this and figured out it was due to the `v` prefix in the tag. Looks like that breaks the (URL resolution here)[https://github.com/cdk8s-team/cdk8s-cli/blob/e81229185e828ed7f5dfad52b1d7dc1afb794582/src/import/crds-dev.ts#L23] a bit. doc.crds.dev will output tags containing the `v` prefix (you and I probably copy-pasted it from the site), so it should probably be supported here 😄

Here's some evidence from my end:
```
~/code/pbcloud-next ↓3
♪ yarn cdk8s import github:projectcontour/contour@v1.25.0
Error: unsupported protocol github:
    at download (/Users/pierce/code/pbcloud-next/.yarn/unplugged/cdk8s-cli-npm-2.64.0-cf582c8fb4/node_modules/cdk8s-cli/lib/util.js:177:19)
    at ImportCustomResourceDefinition.fromSpec (/Users/pierce/code/pbcloud-next/.yarn/unplugged/cdk8s-cli-npm-2.64.0-cf582c8fb4/node_modules/cdk8s-cli/lib/import/crd.js:108:52)
    at matchImporter (/Users/pierce/code/pbcloud-next/.yarn/unplugged/cdk8s-cli-npm-2.64.0-cf582c8fb4/node_modules/cdk8s-cli/lib/import/dispatch.js:35:49)
    at async importDispatch (/Users/pierce/code/pbcloud-next/.yarn/unplugged/cdk8s-cli-npm-2.64.0-cf582c8fb4/node_modules/cdk8s-cli/lib/import/dispatch.js:10:26)
    at async Object.handler (/Users/pierce/code/pbcloud-next/.yarn/unplugged/cdk8s-cli-npm-2.64.0-cf582c8fb4/node_modules/cdk8s-cli/lib/cli/cmds/import.js:31:9)

~/code/pbcloud-next ↓3 ⚠ ERROR
ø yarn cdk8s import github:projectcontour/contour@1.25.0 
Importing resources, this may take a few moments...
projectcontour.io
  projectcontour.io/contourconfiguration
  projectcontour.io/contourdeployment
  projectcontour.io/extensionservice
  projectcontour.io/httpproxy
  projectcontour.io/tlscertificatedelegation
```

**Comment by Vad1mo** [comment]
@pbar1 thank you for your kind response, Indeed this was the issue. 

This is the way to go without the `v`version prefix.

```sh
cdk8s import github:grafana/agent@0.35.4
```

**Comment by pbar1** [comment]
Hey, I wouldn't necessarily call this closed. Take https://doc.crds.dev/github.com/knative/operator for example - the tag one would want to import would also run into this issue without being able to remove the `v` prefix, since it's tag is `knative-v1.11.5` for example.

**Comment by iliapolo** [comment]
Hmm. The `knative-v` tags are definitely unexpected :\
