### ISSUE TITLE
`cdk8s import github:knative/operator@knative-v1.10.2`  results in unsupported protocol github

### ISSUE THREAD

**Issue by Vad1mo** [cdk8s-team/cdk8s#2150]
I am trying to import a CRD that is listed on https://doc.crds.dev/github.com/grafana/agent@v0.35.4 into cdk8s.

From the `cdk8s import --help` I got the description that `cdk8s import github:crossplane/crossplane@0.14.0  Imports constructs for a GitHub repo using doc.crds.dev` should work.

I tried `cdk8s import github:crossplane/crossplane@0.14.0`and the result was successful

```
❯ cdk8s import github:crossplane/crossplane@0.14.0
Importing resources, this may take a few moments...
apiextensions.crossplane.io
  apiextensions.crossplane.io/compositeresourcedefinition
  apiextensions.crossplane.io/composition
pkg.crossplane.io
  pkg.crossplane.io/configuration
  pkg.crossplane.io/configurationrevision
  pkg.crossplane.io/controllerconfig
  pkg.crossplane.io/provider
  pkg.crossplane.io/providerrevision
meta.pkg.crossplane.io
  meta.pkg.crossplane.io/configuration
  meta.pkg.crossplane.io/provider
```

### Description of the bug:

When I however try to import `github:grafana/agent@v0.35.4` I see this error:
```
❯ cdk8s import github:grafana/agent@v0.35.4
Error: unsupported protocol github:
    at download (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/util.js:177:19)
    at ImportCustomResourceDefinition.fromSpec (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/crd.js:108:52)
    at matchImporter (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:35:49)
    at async importDispatch (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:10:26)
    at async Object.handler (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/cli/cmds/import.js:31:9)

```

### Reproduction Steps:

```
cdk8s import github:grafana/agent@v0.35.4
```

### Error Log:

```
Error: unsupported protocol github:
    at download (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/util.js:177:19)
    at ImportCustomResourceDefinition.fromSpec (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/crd.js:108:52)
    at matchImporter (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:35:49)
    at async importDispatch (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:10:26)
    at async Object.handler (/opt/homebrew/Cellar/cdk8s/2.50.0/libexec/lib/node_modules/cdk8s-cli/lib/cli/cmds/import.js:31:9)

```

### Environment:

  - **Framework Version**: cdk8s 2.5.0, as well as older versions 
  - **OS**: MacOS

### Other:

---

This is :bug: Bug Report

**Comment by pecigonzalo** [comment]
Hi, I believe this is still relevant and should be re-opened @iliapolo
