### ISSUE TITLE
Failed to import CRD

### ISSUE THREAD

**Issue by neopointer** [cdk8s-team/cdk8s#2233]
### Description of the bug:

Failed to import CRD, seems to be similar to #892.

### Reproduction Steps:

I could not pin point to the exact place, but it's failing while importing this CRD:

https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.16.3/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumloadbalancerippools.yaml

### Error Log:

```
Error: Key 'of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info' contains non standard characters (Must match regex '/^(\w|\.|\/|-|#|,)*$/')
    at SafeReviver._sanitizeObj (/Users/user/Library/pnpm/global/5/.pnpm/cdk8s-cli@2.198.253/node_modules/cdk8s-cli/lib/reviver.js:40:23)
    at SafeReviver._sanitizeObj (/Users/user/Library/pnpm/global/5/.pnpm/cdk8s-cli@2.198.253/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/Users/user/Library/pnpm/global/5/.pnpm/cdk8s-cli@2.198.253/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/Users/user/Library/pnpm/global/5/.pnpm/cdk8s-cli@2.198.253/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/Users/user/Library/pnpm/global/5/.pnpm/cdk8s-cli@2.198.253/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/Users/user/Library/pnpm/global/5/.pnpm/cdk8s-cli@2.198.253/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/Users/user/Library/pnpm/global/5/.pnpm/cdk8s-cli@2.198.253/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/Users/user/Library/pnpm/global/5/.pnpm/cdk8s-cli@2.198.253/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver.sanitize (/Users/user/Library/pnpm/global/5/.pnpm/cdk8s-cli@2.198.253/node_modules/cdk8s-cli/lib/reviver.js:31:14)
    at safeParseYaml (/Users/user/Library/pnpm/global/5/.pnpm/cdk8s-cli@2.198.253/node_modules/cdk8s-cli/lib/util.js:160:17)
```

### Environment:

  - **Framework Version**: 2.198.253
  - **OS**: MacOS

### Other:

---

This is :bug: Bug Report

**Comment by maliciousbucket** [comment]
Alright, which language are you using and which method are you using to import the CRDs?

By method I mean:

- Using the CLI: `cdk8s import https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.16.3/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumloadbalancerippools.yaml`

- Using cdk8s.yaml:

```yaml
imports:
  - k8s
  - https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.16.3/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumloadbalancerippools.yaml

```
And then running `cdk8s import`

- One of the aforementioned options but with a local version of the file using the path to the file as the URL


I am using Go, Ubuntu, and version 2.198.254 and I was able to install it just fine using the `cdk8s import` command (and yes I understand this setup uses a different OS and version of CDK8s)
![cdk8s-cillium-gen](https://github.com/user-attachments/assets/536be98b-8aaf-4a86-ac76-60918010249c)


![cdk8s-cillium-import](https://github.com/user-attachments/assets/acdf1f6e-9dfa-4562-8b6d-3a543416a43f)

**Comment by neopointer** [comment]
@maliciousbucket sorry I forgot to mention, but I'm using Java. Thanks for taking a look into it.

**Comment by neopointer** [comment]
@maliciousbucket I don't know what happened, but when I tried to import using the URL directly instead of the file in my filesystem then it worked. I would assume then most likely I introduced some change in the local file without noticing.

I'll close the issue. 

Thanks!
