### ISSUE TITLE
Error: Attempted to construct a container from a Container object.

### ISSUE THREAD

**Issue by rickerp** [cdk8s-team/cdk8s#552]
### Description of the bug:
Maybe I'm missing something but I'm creating a Deployment that has a container, his scope is a `cdk8s.Chart(cdk8s.App(), 's')`. 
 
I'm running cdk8s directly inside cdk and when I run `cdk synth` I get the following error:

### Error log
```bash
jsii.errors.JavaScriptError: 
  Error: Attempted to construct a container from a Container object.
      at new Container (/tmp/jsii-kernel-SlexbV/node_modules/cdk8s-plus-17/lib/container.js:99:19)
      at PodTemplate.addContainer (/tmp/jsii-kernel-SlexbV/node_modules/cdk8s-plus-17/lib/pod.js:57:22)
      at /tmp/jsii-kernel-SlexbV/node_modules/cdk8s-plus-17/lib/pod.js:25:48
      at Array.forEach (<anonymous>)
      at new PodSpec (/tmp/jsii-kernel-SlexbV/node_modules/cdk8s-plus-17/lib/pod.js:25:30)
      at new PodTemplate (/tmp/jsii-kernel-SlexbV/node_modules/cdk8s-plus-17/lib/pod.js:124:9)
      at new Deployment (/tmp/jsii-kernel-SlexbV/node_modules/cdk8s-plus-17/lib/deployment.js:51:29)
      at /tmp/tmpieawnqxz/lib/program.js:8154:58
      at Kernel._wrapSandboxCode (/tmp/tmpieawnqxz/lib/program.js:8582:24)
      at Kernel._create (/tmp/tmpieawnqxz/lib/program.js:8154:34)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rickerp/git/devops-training/deployments/aws-cdk/app.py", line 55, in <module>
    Stack(app, Settings())
  File "/home/rickerp/.local/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/rickerp/git/devops-training/deployments/aws-cdk/app.py", line 51, in __init__
    cluster.add_cdk8s_chart(id="Chart", chart=Chart(api_image_uri, settings))
  File "/home/rickerp/.local/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/rickerp/git/devops-training/deployments/aws-cdk/k8s.py", line 10, in __init__
    api = kplus.Deployment(
  File "/home/rickerp/.local/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/rickerp/.local/lib/python3.9/site-packages/cdk8s_plus_17/__init__.py", line 4483, in __init__
    jsii.create(Deployment, self, [scope, id, props])
  File "/home/rickerp/.local/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 275, in create
    response = self.provider.create(
  File "/home/rickerp/.local/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/home/rickerp/.local/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Attempted to construct a container from a Container object.
Subprocess exited with error 1
```

### Reproduction Steps:
cdk.json
```python3
{
  "app": "python3 app.py",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
    "@aws-cdk/aws-secretsmanager:parseOwnedSecretName": true,
    "@aws-cdk/aws-kms:defaultKeyPolicies": true,
    "@aws-cdk/aws-s3:grantWriteWithoutAcl": true,
    "@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount": true
  }
}
```
app.py
```python3
from aws_cdk import core as cdk, aws_eks as eks
import cdk8s as k
import cdk8s_plus_17 as kplus

class Chart(k.Chart):
    def __init__(self):
        super().__init__(k.App(), "MyCDK8sChart")
        api = kplus.Deployment(self, 'MyDeployment', containers=[kplus.Container(image='alpine:latest')])

class Stack(cdk.Stack):
    def __init__(self, scope: cdk.Construct):
        super().__init__(scope, "MyStack")
        cluster = eks.Cluster(self, "MyCluster", version=eks.KubernetesVersion.V1_19)
        cluster.add_cdk8s_chart("MyChart", chart=Chart())

app = cdk.App()
Stack(app)
app.synth()
```
```bash
$ cdk synth
```

### Environment:
  - Python 3.9.2
  - **Frameworks Versions**: 
    -   "aws-cdk.core==1.94.1",
    -   "aws-cdk.aws-eks==1.94.1",
    -   "cdk8s==1.0.0b10",
    -   "cdk8s-plus-17==1.0.0b10",
  - **OS**: Linux Arch

--- 

This is :bug: Bug Report

**Comment by rickerp** [comment]
## EDIT
Found what's causing this is that **cdk8s-plus** is creating a container in the back with the elements inside the `containers` list (argument of `kplus.Deployment`) but in the [documentation](https://cdk8s.io/docs/latest/plus/#getting-started) you have to create the Class  

Solution: 
```python3
api = kplus.Deployment(self, 'MyDeployment', containers=[{'image': 'alpine:latest'}])
```
