### ISSUE TITLE
CDK8s import - 1.19 Kubernetes API Spec is Missing

### ISSUE THREAD

**Issue by CAR6807** [cdk8s-team/cdk8s#616]
### Description of the bug:

cdk8s import fails when trying to import API version higher than 1.18 

cdk8s import k8s@1.19.0 --language typescript

### Reproduction Steps:

cdk8s import k8s@1.19.0 --language typescript

### Error Log:

/usr/local/Cellar/cdk8s/0.33.0/libexec/lib/node_modules/cdk8s-cli/lib/util.js:74
                    throw new Error(`${res.statusMessage}: ${url}`);
                    ^

Error: Not Found: https://raw.githubusercontent.com/instrumenta/kubernetes-json-schema/master/v1.19.0/_definitions.json
    at ClientRequest.client.get.res (/usr/local/Cellar/cdk8s/0.33.0/libexec/lib/node_modules/cdk8s-cli/lib/util.js:74:27)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:546:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:432:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
S286443:hpav2betav2 car6807$ NODE_TLS_REJECT_UNAUTHORIZED=0 cdk

### Environment:

  - **Framework Version**:
  - **OS**:

### Other:

--- 

This is :bug: Bug Report

**Comment by clintmod** [comment]
You'll need to update the latest 1.0 beta versions to get this to work.

**Comment by clintmod** [comment]
You'll also need to be aware of this change https://github.com/cdk8s-team/cdk8s/pull/421 

Object names have changed

Service -> KubeService
Deployment -> KubeDeployment
