### ISSUE TITLE
[GO] another type was already registered with cdk8s.ApiObject

### ISSUE THREAD

**Issue by Hunter-Thompson** [cdk8s-team/cdk8s#648]
### Description of the bug:

While trying to synth my Go project, I get the following error:

```
panic: another type was already registered with cdk8s.ApiObject: {cdk8s.ApiObject 1}

goroutine 1 [running]:
github.com/aws/jsii-runtime-go/runtime.RegisterClass(0x6c2e1e, 0xf, 0x82cd08, 0x6938c0, 0xc0000e99a8, 0xd, 0xd, 0x7f27e8)
        /home/hunter/asd/test/vendor/github.com/aws/jsii-runtime-go/runtime/runtime.go:58 +0x18a
github.com/cdk8s-team/cdk8s-go/cdk8s.init.0()
        /home/hunter/asd/test/vendor/github.com/cdk8s-team/cdk8s-go/cdk8s/cdk8s.init.go:10 +0x825
exit status 2
```

### Reproduction Steps:

```go

package main

import (
	"github.com/aws/constructs-go/constructs/v3"
	"github.com/aws/jsii-runtime-go"
	"github.com/cdk8s-team/cdk8s-core-go/cdk8s"
	"github.com/opencdk8s/cdk8s-argo-rollouts-go/opencdk8scdk8sargorollout"
)

type MyChartProps struct {
	cdk8s.ChartProps
}

func NewMyChart(scope constructs.Construct, id string, props *MyChartProps) cdk8s.Chart {
	var cprops cdk8s.ChartProps
	if props != nil {
		cprops = props.ChartProps
	}
	chart := cdk8s.NewChart(scope, jsii.String(id), &cprops)

	opencdk8scdk8sargorollout.NewArgoRollout(chart, jsii.String("asd"), &opencdk8scdk8sargorollout.ArgoRolloutProps{
		Metadata: nil,
		Spec:     nil,
	})
	return chart
}

func main() {
	app := cdk8s.NewApp(nil)
	NewMyChart(app, "test", nil)
	app.Synth()
}
```

### Environment:

  - **Framework Version**:
```
v1.0.0-beta.30
```
  - **OS**:
  
  ```
  → uname -a
Linux owl-farm 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

--- 

This is :bug: Bug Report

**Comment by Hunter-Thompson** [comment]
Turns out it was because of mismatched dependencies. Making sure both the package, and your chart have the same cdk8s version is important.
