### ISSUE TITLE
BUG cdk8s.Include: unable to determine protocol from url: ${url} 

### ISSUE THREAD

**Issue by kevinglasson** [cdk8s-team/cdk8s#678]
### Description of the bug:
I am unable to make the `Include` work in Python to include a `.yaml` file.

I have tried many things to get it to work.
- relative path
- absolute path
- file:// protocol
- single quoting inside the string

### Reproduction Steps:
```
cdk8s.Include(self, "tools", url=f"./manifests/tools-deployment.yaml")
```

### Error Log:
```
cdk diff --all
```

```
/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/_loadurl.js:26
    throw new Error(`unable to determine protocol from url: ${url}`);
    ^

Error: unable to determine protocol from url: ./manifests/tools-deployment.yaml
    at Object.<anonymous> (/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/_loadurl.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
jsii.errors.JavaScriptError: 
  Error: Command failed: /usr/local/Cellar/node/16.8.0/bin/node /private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/_loadurl.js ./manifests/tools-deployment.yaml
  /private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/_loadurl.js:26
      throw new Error(`unable to determine protocol from url: ${url}`);
      ^
  
  Error: unable to determine protocol from url: ./manifests/tools-deployment.yaml
      at Object.<anonymous> (/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/_loadurl.js:26:11)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
      at node:internal/main/run_main_module:17:47
  
      at checkExecSyncError (node:child_process:826:11)
      at Object.execFileSync (node:child_process:864:15)
      at loadurl (/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/yaml.js:106:28)
      at Function.load (/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/yaml.js:75:22)
      at new Include (/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/include.js:24:37)
      at /private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/tmpl6if523q/lib/program.js:8367:58
      at Kernel._wrapSandboxCode (/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/tmpl6if523q/lib/program.js:8795:24)
      at Kernel._create (/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/tmpl6if523q/lib/program.js:8367:34)
      at Kernel.create (/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/tmpl6if523q/lib/program.js:8108:29)
      at KernelHost.processRequest (/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/tmpl6if523q/lib/program.js:9692:36)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kevinglasson/Development/LITEC/sdm/src/cloud/infra/app.py", line 46, in <module>
    kube_apps = KubeAppsStack(
  File "/Users/kevinglasson/Development/LITEC/sdm/src/cloud/venv/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/kevinglasson/Development/LITEC/sdm/src/cloud/infra/infra/apps/kube_apps.py", line 79, in __init__
    SdmChart(
  File "/Users/kevinglasson/Development/LITEC/sdm/src/cloud/venv/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/kevinglasson/Development/LITEC/sdm/src/cloud/infra/infra/apps/sdm/sdm.py", line 48, in __init__
    tools = cdk8s.Include(self, "tools", url=f"./manifests/tools-deployment.yaml")
  File "/Users/kevinglasson/Development/LITEC/sdm/src/cloud/venv/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/kevinglasson/Development/LITEC/sdm/src/cloud/venv/lib/python3.9/site-packages/cdk8s/__init__.py", line 1096, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/Users/kevinglasson/Development/LITEC/sdm/src/cloud/venv/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 290, in create
    response = self.provider.create(
  File "/Users/kevinglasson/Development/LITEC/sdm/src/cloud/venv/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/Users/kevinglasson/Development/LITEC/sdm/src/cloud/venv/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Command failed: /usr/local/Cellar/node/16.8.0/bin/node /private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/_loadurl.js ./manifests/tools-deployment.yaml
/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/_loadurl.js:26
    throw new Error(`unable to determine protocol from url: ${url}`);
    ^

Error: unable to determine protocol from url: ./manifests/tools-deployment.yaml
    at Object.<anonymous> (/private/var/folders/z1/7z6ky5t17dx1mdp9z66rqx000000gn/T/jsii-kernel-A4AAec/node_modules/cdk8s/lib/_loadurl.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

Subprocess exited with error 1
```

### Environment:
```
# python
Python 3.9.7

# pip
cdk8s==1.0.0b46

# yarn / npm
cdk8s-cli==1.0.0-beta.50
```

--- 

This is :bug: Bug Report

**Comment by kevinglasson** [comment]
Okay, this was my fault.

This is a part of a larger 'cdk' application and I was accidentally passing through the wrong 'scope'. Once I changed it to a 'cdk8s.App()' like it's supposed to be it worked fine!
