### ISSUE TITLE
init timeouts within corporate network

### ISSUE THREAD

**Issue by mailtoraja18** [cdk8s-team/cdk8s#765]
$ cdk8s init java-app
C:\Users\r016006\Scratch\ds\.npm12\node_modules\cdk8s-cli\node_modules\cdk8s\lib\_loadurl.js:39
    throw new Error(`http error: ${err.message}`);
    ^

Error: http error: connect ETIMEDOUT 104.16.16.35:80
    at RedirectableRequest.<anonymous> (C:\Users\r016006\Scratch\ds\.npm12\node_modules\cdk8s-cli\node_modules\cdk8s\lib\_loadurl.js:39:11)
    at Object.onceWrapper (events.js:421:26)
    at RedirectableRequest.emit (events.js:314:20)
    at ClientRequest.eventHandlers.<computed> (C:\Users\r016006\Scratch\ds\.npm12\node_modules\cdk8s-cli\node_modules\cdk8s\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:427:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by mailtoraja18** [comment]
tried setting proxy in npm config - does not help

**Comment by Chriscbr** [comment]
Hi @mailtoraja18 - as a workaround, can you try passing the `--check-upgrade false` when you are initializing your project? By default cdk8s checks if you have the latest version when you create a new project, but passing this flag should override it.

I think I've seen this issue reported before - I wonder if it might be appropriate to set a smaller timeout for this network request and to catch the errors explicitly since it doesn't make sense to stop the user from creating a project if checking for upgrades fails.
