### ISSUE TITLE
CRD regex sanitize does not allow spaces

### ISSUE THREAD

**Issue by jeverett1522** [cdk8s-team/cdk8s#892]
### Description of the bug:
When trying to import a CRD the `API Version` key is failing because it doesn't match the regex match.  The regex that is shown should match `'/^(\w|\.|\/|-|#|,)*$/'` which does not allow spaces.  No spaces means that the description key will fail or it is failing on something else.  The key specifically looks like this:
```
        API Version:
          Description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          Type:         string
```

### Reproduction Steps:
Command I ran: `cdk8s import --language python`
```
# cdk8s.yaml
language: python
app: pipenv run python main.py
imports:
  - k8s
  - testapp:=my-app.yaml
```

### Error Log:
```
Error: Key 'API Version' contains non standard characters (Must match regex '/^(\w|\.|\/|-|#|,)*$/')
    at SafeReviver._sanitizeObj (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/lib/reviver.js:40:23)
    at SafeReviver._sanitizeObj (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver.sanitize (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/lib/reviver.js:31:14)
    at safeParseYaml (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/lib/util.js:105:17)
    at safeParseCrds (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/lib/import/crd.js:147:46)
    at Function.fromSpec (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/lib/import/crd.js:120:51)
    at async importDispatch (/usr/local/Cellar/cdk8s/1.0.143/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:9:26)
```

### Environment:

  - **Framework Version**: 1.0.143
  - **OS**: macOS Big Sur 11.6.4
  - **python**: 2.7.16
  - **pipenv**: 2022.3.28

### Other:

---

This is :bug: Bug Report

**Comment by jeverett1522** [comment]
This was my mistake, it was a miss configuration.
